### ISSUE TITLE
Different sized buffer than the output size causing problem

### ISSUE THREAD

**Issue by Smithangshu** [frzi/blinkjs#14]
Hi,

Thanks for releasing such a great library. It's the most flexible GPGPU library I have found. But I am getting an error. When I am doing as following.

`
       let a = new blink.Buffer({ data: new Int32Array([1, 2, 3, 4, 5, 6]), type: blink.INT32, vector: 1 });
        let b = new blink.Buffer({ alloc: 5, type: blink.INT32, vector: 1 });
        let kernel = new blink.Kernel({ input: { 'a': a }, output: { 'b': b } },
           'void main() 
            {
                b = texture(a, bl_UV).r;
            }');
        kernel.exec();
        for (let i = 0; i < 5; i++) {
            console.log('Value at ${i} is ${b.data[i]}.')
        }
`

Means, I am sending output buffer size as 5 but the size my input buffer 6 or might be some larger value, it results very weird. Sometime we need to pass larger input buffer. Also, I am not sure, if I can pass a buffer through uniforms using "exec()" function key-value pair.  I need to pass a few very large buffers as input and I need to get comparatively smaller output buffer. Is it possible? 

Can you please help me to sort out this issue? Thanks in advance.

**Comment by frzi** [comment]
Hello,

`bl_UV` describes the current UV coordinate of the output texture. It's not particularly useful when you want to read from input textures whose dimensions differ from the output texture. In your example, buffer `a` has 6 values and thus results in a texture of 2x3. Whereas buffer `b` (the output) has 5 values and thus has a texture of 1x5. Due to the conflicting dimensions `bl_UV` will be of little use here. 😅 

To get around this you will need to manually calculate the coordinates for the texture(s) you're trying to read from. In this case, `bl_Id()` could help you here.

As an example, here is a slightly generic function that allows you to read from a texture based on an index:
```glsl
int valueOf(isampler2D buff, uint index) {
	int i = int(index);
	ivec2 size = textureSize(buff, 0);
	ivec2 coord = ivec2(i % size.x, i / size.x);
	return texelFetch(buff, coord, 0).r;
}
```
which you can use like this:
```glsl
void main() {
	b = valueOf(a, bl_Id());
}
```

>  Also, I am not sure, if I can pass a buffer through uniforms using "exec()" function key-value pair. I need to pass a few very large buffers as input and I need to get comparatively smaller output buffer. Is it possible?

Not as an uniform, no. *But* you can declare them as inputs and override them later on before executing:
```js
const kernel = new blink.Kernel({
	input: { a },
	output: { b }
}, /* glsl code */)

kernel.inputs.a = c // Assign a different buffer for input `a`.

kernel.exec()
```
The only restriction is that the newly assigned buffer is of the same type. (float, int, uint)

Hope this helped you enough. Thanks for checking out blink.js!

P.S.: It's been a while since I've worked on this framework, so I'm a bit rusty with it myself! 😅

**Comment by Smithangshu** [comment]
Hi, 
Thanks a lot it works perfectly. I have another question is it possible to keep a very large array around 60 million values in GPU and access & use it when needed from different kernels across the whole program? Also, I never need it transfer completely to CPU, only sometime, I need to take value some indexes of it. Can it be done and moreover is it a good idea to keep large array(texture) in GPU across program lifecycle?

**Comment by frzi** [comment]
You can use buffers across multiple kernels, yes. If you have data you mainly want to keep on the GPU and don't plan on transferring to CPU back-and-forth, then you should use [`blink.DeviceBuffer`](https://github.com/frzi/blinkjs#devicebuffer). 

I can't tell you whether it's a good idea to keep 60 million values in VRAM or not. This really depends on your app and your userbase. Keep in mind that 60 million 32-bit integers/floats is around 230 MB. (V)RAM on mobile devices (and laptops) tend to be more scarce than on desktops with dedicated GPUs. It's entirely up to you to decide what is and what isn't a reasonable amount of VRAM usage.

**Comment by Smithangshu** [comment]
This library works like charm, you have done a great job. And you are right about the VRAM issue. I think its not a very good idea.
One more thing to ask, can I use this library on iOS Safari?

**Comment by frzi** [comment]
Yes and no. WebGL 2 should be enabled on iOS 15, expected to release later this year. However, you will not be able to write to buffers with type `blink.FLOAT`, as this requires the `EXT_color_buffer_float` extension - which Safari does not/will not support for the time being (or if ever).
