### ISSUE TITLE
2d_coordinates

### ISSUE THREAD

**Issue by christofelfferich** [frzi/blinkjs#9]
Hello, thank you for your work. When running a shader on the imagedata object from a 2d canvas context, I cannot find a reference to the x and y coordinate of the current fragment/pixel on the canvas. gl_FragCoord.y seems to be working but gl_FragCoord.x seems not correct. bl_UV behaves similar but in the range 0-1. Is there a way to get the x and y coordinate for example within the grayscale example? I might be missing something. Thanks!

**Comment by frzi** [comment]
Hi! 
Could you be a bit more specific when you mean `gl_FragCoord.x` seems to be incorrect? 

Keep in mind when working with Canvas data: the pixel date is stored in a `Uint8ClampedArray`, which means values are clamped between 0-255. This means it's impossible to store values beyond this range. If you need to store values beyond this range, the pixel data will have to be copied to another TypedArray (e.g. `Uint32Array`). Though this data cannot be placed directly into the Canvas then.

I just tested `gl_FragCoord.xy` with the following code:
```js
const kernelSource = `
	void main() {
		vec2 xy = gl_FragCoord.xy;
		out_rgba = uvec4(uvec2(xy), 0, 255);
	}`

const canvas = document.createElement('canvas')
canvas.width = canvas.height = 256
document.body.appendChild(canvas)

const ctx = canvas.getContext('2d')

const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)

const buffer = new blink.Buffer({
	data: imageData.data,
	vector: 4,
})

const kernel = new blink.Kernel({
	output: { out_rgba: buffer }
}, kernelSource)

kernel.exec()

ctx.putImageData(imageData, 0, 0)

kernel.delete()
buffer.delete()
```

Which produces the following image:

![download](https://user-images.githubusercontent.com/8537579/64063034-0a2f3900-cbef-11e9-8c9b-5f347997b86c.png)

Thanks for your comment!

**Comment by christofelfferich** [comment]
Hi, thank you for your swift reply. I tried your example and get the same result. I noticed It occurs only when the width of the canvas is smaller than or greater than a certain value. I tried both with a Uint32Array and a Uint8 array and it makes no difference for this matter: the gl_FragCoord_x value seems to be the problem. Thanks!

![xscreenshot-20190831T111331](https://user-images.githubusercontent.com/8147153/64064203-b2003300-cbfe-11e9-8321-41d8f651bf09.png)
![xscreenshot-20190831T111355](https://user-images.githubusercontent.com/8147153/64064215-b9274100-cbfe-11e9-8ce3-41256d723272.png)
![xscreenshot-20190831T143819](https://user-images.githubusercontent.com/8147153/64064219-bf1d2200-cbfe-11e9-8609-2e7da58baed0.png)
![xscreenshot-20190831T143841](https://user-images.githubusercontent.com/8147153/64064221-c17f7c00-cbfe-11e9-8c47-af04fe9b4343.png)

**Comment by christofelfferich** [comment]
I tried the example with a Uint32 array:                         

> out_buffer = uint((255 << 24) | (0 << 16) | (int(xy.y) << 8) | int(xy.x));

It has a similar outcome.

**Comment by christofelfferich** [comment]
![xscreenshot-20190831T151436](https://user-images.githubusercontent.com/8147153/64064576-a3684a80-cc03-11e9-87ca-ecbc35d4cbae.png)
![xscreenshot-20190831T151548](https://user-images.githubusercontent.com/8147153/64064577-a400e100-cc03-11e9-897d-55d1c9c2972c.png)

**Comment by frzi** [comment]
Ahaha. Well, I think I know what's happening. 

Dimensions (as in, width and height) aren't a thing for Buffers. Buffer data is always considered as a 1D array of values. However, because **blink.js** uses the rendering pipeline to perform the shader (as compute shaders aren't a thing... yet), it *needs* a width and a height. It does this by calculating the first possible width and height using [`closestDimensions()`](https://github.com/frzi/blinkjs/blob/5dd593f778578866d7741b40e78dc9648c95107b/src/common.js#L85), which is purely based on the [length of the 1D data array](https://github.com/frzi/blinkjs/blob/5dd593f778578866d7741b40e78dc9648c95107b/src/Buffer.js#L33). In other words, **blink.js** performs with different dimensions than those of the Canvas' pixel data, rendering `gl_FragCoord` pretty useless in this case, unfortunately. 

This means **blink.js** is not really suitable for image processing that rely on coordinates of said image.

A possible idea for a future feature is to force a Kernel to perform at a user specified resolution.

I hope I explained the issue clearly. :)

**Comment by christofelfferich** [comment]
Very clear! I hard coded the dimensions for my setup in the buffer constructor and it did the trick. :) I will override the buffer constructor and will move on with my experiments using blink.js. Thanks a bunch for looking into it!
